### PR TITLE
Aws cur reports ex docs

### PR DESCRIPTION
**Pull request by davidesner**

### CODE REVIEW

**Comment by davidesner** [comment]
Hi @odinuv here's another one to be published.

**Review by odinuv — APPROVED** [review]
still don't understand why can't you choose the reviewers

**Comment by ujovlado** [comment]
> still don't understand why can't you choose the reviewers

spam protection ... imagine every github user could be able to send you a review request and you have  notifications turned on ;)

**Comment by odinuv** [comment]
and mentions? :) afaik David is even org collaborator

**Comment by ujovlado** [comment]
> and mentions? :) afaik David is even org collaborator

good point 😱  ... anyway, David has access only to 3 repos (connection-docs is not one of them)

**Pull request merged**
