### PR TITLE
Docs improvement for development branches

### PR DESCRIPTION
**Pull request by tomasfejfar**
Mostly about conflics, reset to default and merging.

### CODE REVIEW

**Comment by ujovlado** [comment]
@tomasfejfar new default branch is main. Would it be possible to rebase this if PR is still valid? Thanks!

**Comment by ujovlado** [comment]
Rebasnute.

**Comment by ujovlado** [comment]
@tomasfejfar do you have a plan to finish this? If not, let's close it.

**Comment by tomasfejfar** [comment]
Nechám branch s commity, abych to mohl vytahnout, když se do toho bude dál hrabat :)

**Pull request closed without merging**
