### PR TITLE
Update info about sharing to specific users

### PR DESCRIPTION
**Pull request by fejjo**
Jira issue https://keboola.atlassian.net/browse/KBC-66

Closed: https://github.com/keboola/connection-docs/pull/193

### CODE REVIEW

**Comment by fejjo** [comment]
A co tak  `To **specified users**. Any listed project users **in the organization** can use the data bucket.` Ten popisok mi prave pride podobny uz teraz, alebo to mam este definovat viac ako to bolo v tom starom PR chcel som to nechat prave podobne jak je to v Slected Projects

**Comment by odinuv** [comment]
a kdyz uz jsi v tom tak prosimte zmen " can use the data bucket." na " can link the data bucket." i v tech ostatnich odrazkach

**Comment by fejjo** [comment]
Upravene

**Comment by odinuv** [comment]
si jednu vynechal :)

**Comment by fejjo** [comment]
Jo dik :) som to dal vyhladat `can use the data bucket.`a v tom jednom pripade tam ta '.' nieje :)

**Pull request merged**
