### PR TITLE
Remove Connection from Storage Ex and WR

### PR DESCRIPTION
**Pull request by davidesner**
Rename Keboola Connection Storage components to Keboola Storage. Connection is no longer used when talking about the platform...

### CODE REVIEW

**Comment by hhanova** [comment]
However, the components in the UI are still called this way. That's why I did not rename them in the docs when I did the others.

Will you remove "Connection" from their names and description in the UI as well, please?

Thanks!

**Comment by pavel-synek** [comment]
Yes, agreed with @hhanova - we need to push for consistency in our naming convention. I can see it has already been renamed on components.keboola.com, let us clean the rest.

**Review by pavel-synek — APPROVED** [review]

**Comment by hhanova** [comment]
It's just that the whole thing (components.keboola.com) is called `Create your component for Keboola **Connection**`  :-)))

**Comment by hhanova** [comment]
@davidesner thank you for editing the UI so quickly! I've made changes in the other two docs files and navigation. 
You can merge it.

**Pull request merged**
