### PR TITLE
readOnly access with external buckets has a limitation alert

### PR DESCRIPTION
**Pull request by romanbracinik**
Jira issue(s):  https://keboola.atlassian.net/browse/PROOF-185

Changes:

- add information about read only and external buckets limitation in snowflake

---

### CODE REVIEW

**Comment by romanbracinik** [comment]
Screenshot 2024-03-20 at 19 37 00

**Comment by jirkasemmler** [comment]
za me ok, pockame na ten proofreading

**Review by hhanova — APPROVED** [review]

**Comment by jirkasemmler** [comment]
@romanbracinik merguju a zaviram task

**Pull request merged**
