### PR TITLE
add sydney region url and its ips

### PR DESCRIPTION
**Pull request by kacurez**
prida info o region a ip adresach ktore som zobral zo zoznamu Elastic IPs v
https://ap-southeast-2.console.aws.amazon.com/vpc/home?region=ap-southeast-2#Addresses:sort=PublicIp

### CODE REVIEW

**Comment by odinuv** [comment]
zaktualizovat https://help.keboola.com/extractors/ip-addresses/kbc-public-ip.json

**Comment by kacurez** [comment]
pozeram ze v `kbc-public-ip.json` je len us region
https://github.com/keboola/connection-docs/blob/master/extractors/ip-addresses/kbc-public-ip.json
btw ako sa to generuje? pride mi ze to je z niecoho generovane.

**Comment by Halama** [comment]
negeneruje se to imho ničím. Tak tu EU tam prosím doplň taky.

**Comment by kacurez** [comment]
pridal som to tam

**Comment by Halama** [comment]
Říkal bych tady tomu taky `AUS` místo `AP` viz. https://github.com/keboola/connection/pull/1527#issuecomment-421347564

**Comment by kacurez** [comment]
som ten commit pomenoval opacne :) malo byt `AP -> AUS`

**Pull request merged**
